# Generated by Django 3.0.7 on 2020-07-04 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20200704_1459'),
        ('posts', '0002_auto_20200704_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='topics.Topic'),
        ),
    ]
