# Generated by Django 3.0.7 on 2020-07-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200704_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Topic',
            new_name='topic',
        ),
    ]
